### PR TITLE
Migrate config.yml to config.hjson

### PR DESCRIPTION
**Pull request by PiggleMcDiggle**
HJSON config variant

### CODE REVIEW

**Comment by Peter-Crawley** [comment]
On my phone otherwise I would do this myself:
- Please rename the file to use the .hjson file extension

**Comment by Peter-Crawley** [comment]
Requires #14

**Comment by Peter-Crawley** [comment]
I will write code to handle hjson config loading later.

**Comment by PiggleMcDiggle** [comment]
This can be merged now?

**Pull request merged**
